plugins { id 'java' }
group = 'ru.example'

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url = 'https://repo.luckperms.net/' }
}

dependencies {
    compileOnly libs.spigot.api
    compileOnly project(':vkchat_core')
    compileOnly libs.luckperms.api
    implementation libs.json
}

tasks.withType(JavaCompile) { options.encoding = 'UTF-8'; options.release = 17 }
