name: VKChatOffline
version: 3.0.0
main: ru.example.vkchatoffline.VKChatOfflinePlugin
api-version: "1.16"
depend: [VKChat]
commands:
  stash:
    description: Получить награды из оффлайн-приключений
    aliases: [тайник, склад, сейф]
    permission: vkchat.offline.player
permissions:
  vkchat.offline.player:
    description: Доступ к /stash и оффлайн-приключениям
    default: true
