name: VKChatArtifacts
version: 3.2.0
main: ru.example.vkchatartifacts.VKChatArtifactsPlugin
api-version: "1.16"
depend: [VKChat]
softdepend: [VKChatGear, VKChatMarket]
permissions:
  vkchat.artifacts.player:
    description: Доступ к просмотру и использованию магазина артефактов
    default: true
