plugins {
    id 'java'
}

group = 'ru.example'

repositories {
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    compileOnly libs.spigot.api
    compileOnly project(':vkchat_core')
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand version: version
    }
}
