name: VKChatMarket
version: "2.0.0"
main: ru.example.vkchatmarket.VKChatMarketPlugin
api-version: "1.16"
depend: [VKChat]
commands:
  market:
    description: Открыть меню динамической экономической биржи торговли
    aliases: [sell, shop, рынок, биржа]
    permission: vkchat.market.player
permissions:
  vkchat.market.player:
    description: Доступ к использованию экономической биржи покупки/продажи ресурсов
    default: true
