name: VKChatMarket
version: 3.2.0
main: ru.example.vkchatmarket.VKChatMarketPlugin
api-version: "1.16"
depend: [VKChat]
softdepend: [ExcellentEnchants, PlaceholderAPI]
commands:
  market:
    description: Открыть меню динамической экономической биржи торговли
    aliases: [sell, shop, рынок, биржа]
    permission: vkchat.market.player
  mkta:
    description: Администрирование биржи
    aliases: [marketadmin]
    permission: vkchat.market.admin
permissions:
  vkchat.market.player:
    description: Доступ к использованию экономической биржи покупки/продажи ресурсов
    default: true
  vkchat.market.admin:
    description: Администрирование биржи (reload, stats, setprice)
    default: op
