name: VKChatMobs
version: 3.2.0
main: ru.example.vkchatmobs.VKChatMobsPlugin
api-version: "1.16"
depend: [VKChat, VKChatGear, VKChatArtifacts, VKChatNations]
commands:
  mobs:
    description: Управление контрактами на охоту за мобами.
    aliases: [mob]
  contract:
    description: Посмотреть текущий охотничий контракт.
    aliases: [contracts]

permissions:
  vkchatmobs.admin:
    description: Админ-команды VKChatMobs
    default: op
