plugins {
    id 'java'
}

group = 'ru.example'

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    compileOnly libs.spigot.api
    compileOnly libs.placeholderapi
    compileOnly libs.vaultapi
    compileOnly libs.jsr305

    implementation libs.hikaricp
    implementation libs.json
    implementation libs.jbcrypt
}

jar {
    archiveBaseName.set('VKChat')
    archiveClassifier.set('all')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
