name: VKChatJobs
version: 3.2.0
main: ru.example.vkchatjobs.VKChatJobsPlugin
api-version: "1.16"
depend: [VKChat]
commands:
  jobs:
    description: Открыть интерактивное игровое меню профессий и навыков
    aliases: [работы, job, навыки]
    permission: vkchat.jobs.player
permissions:
  vkchat.jobs.player:
    description: Доступ к использованию профессий и открытию меню работ
    default: true
